### PR TITLE
Feat: group array item by its length in related values panel.

### PR DESCRIPTION
**Pull request by cesaryuan**
#124

### CODE REVIEW

**Comment by ericallam** [comment]
Good idea! Could we change it so the output is `Array(${length})` instead? So if it was an array of length 4 it would be shown as `Array(4)`

**Comment by cesaryuan** [comment]
> Good idea! Could we change it so the output is `Array(${length})` instead? So if it was an array of length 4 it would be shown as `Array(4)`

Hi, thanks for you reply. It's a good advice and  I have changed to it. You can check it.

**Comment by cesaryuan** [comment]
I'm still wondering if there is a better format for object item (`"{...}"`). Do you have any idea? 😊

**Comment by ericallam** [comment]
Sorry don't have any ideas for the object, but if you come up with anything please open another PR :)

**Pull request merged**
