### PR TITLE
Adding a toast error message to the homepage for errors in JSON

### LINKED ISSUE #77: Implement error message when JSON is invalid syntax

### PR DESCRIPTION
**Pull request by kubahasek**
Closes #77 

Adds a toast to the homepage when there is an error in parsing the JSON provided.

### CODE REVIEW

**Comment by ericallam** [comment]
I just made a bunch of changes to get this to work, and pushed them to a branch on our repo. You can see the commit here: 

https://github.com/apihero-run/jsonhero-web/commit/12e31d02e9af1b85686c69f887787f0b144c113a

If you can grab those changes and merge them into this PR, then we are in business

**Comment by kubahasek** [comment]
@ericallam Do I understand correctly that I need to pull and merge my code with the changes you made and then we can merge?

**Comment by ericallam** [comment]
@kubahasek any luck with the merge? Anything I could help with?

**Review by kubahasek — COMMENTED** [review]
Merged main

**Comment by kubahasek** [comment]
@ericallam Should be done now! Sorry, was swamped with school stuff so only got to it.

**Comment by ericallam** [comment]
Thanks! Will take a look at this tomorrow and hopefully get it merged 👍

**Comment by ericallam** [comment]
@kubahasek it looks like you merged in main, but I made the changes in this branch: 

https://github.com/apihero-run/jsonhero-web/tree/kubahasek-issue-77

It might be easiest at this point to start a new PR, without the merge from main

**Comment by kubahasek** [comment]
Alright, I will do that, sorry about that.

**Pull request closed without merging**
